//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.36010
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalDBClienteServicios.ServiceReferenceListarTodosLosUsers {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usersDTO", Namespace="http://schemas.datacontract.org/2004/07/Dominio.Dtos")]
    [System.SerializableAttribute()]
    public partial class usersDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime create_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime date_of_birthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int departments_id_departmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fullnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_departmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> last_acces_datexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<int> messages1_id_messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<int> messages_id_messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string professionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int roleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<int> users_acts_id_user_actField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<int> users_workgroups_id_users_workgroupsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime create_date {
            get {
                return this.create_dateField;
            }
            set {
                if ((this.create_dateField.Equals(value) != true)) {
                    this.create_dateField = value;
                    this.RaisePropertyChanged("create_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date_of_birth {
            get {
                return this.date_of_birthField;
            }
            set {
                if ((this.date_of_birthField.Equals(value) != true)) {
                    this.date_of_birthField = value;
                    this.RaisePropertyChanged("date_of_birth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int departments_id_department {
            get {
                return this.departments_id_departmentField;
            }
            set {
                if ((this.departments_id_departmentField.Equals(value) != true)) {
                    this.departments_id_departmentField = value;
                    this.RaisePropertyChanged("departments_id_department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fullname {
            get {
                return this.fullnameField;
            }
            set {
                if ((object.ReferenceEquals(this.fullnameField, value) != true)) {
                    this.fullnameField = value;
                    this.RaisePropertyChanged("fullname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_department {
            get {
                return this.id_departmentField;
            }
            set {
                if ((this.id_departmentField.Equals(value) != true)) {
                    this.id_departmentField = value;
                    this.RaisePropertyChanged("id_department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_user {
            get {
                return this.id_userField;
            }
            set {
                if ((object.ReferenceEquals(this.id_userField, value) != true)) {
                    this.id_userField = value;
                    this.RaisePropertyChanged("id_user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> last_acces_datex {
            get {
                return this.last_acces_datexField;
            }
            set {
                if ((this.last_acces_datexField.Equals(value) != true)) {
                    this.last_acces_datexField = value;
                    this.RaisePropertyChanged("last_acces_datex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<int> messages1_id_message {
            get {
                return this.messages1_id_messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messages1_id_messageField, value) != true)) {
                    this.messages1_id_messageField = value;
                    this.RaisePropertyChanged("messages1_id_message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<int> messages_id_message {
            get {
                return this.messages_id_messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messages_id_messageField, value) != true)) {
                    this.messages_id_messageField = value;
                    this.RaisePropertyChanged("messages_id_message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string profession {
            get {
                return this.professionField;
            }
            set {
                if ((object.ReferenceEquals(this.professionField, value) != true)) {
                    this.professionField = value;
                    this.RaisePropertyChanged("profession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int role {
            get {
                return this.roleField;
            }
            set {
                if ((this.roleField.Equals(value) != true)) {
                    this.roleField = value;
                    this.RaisePropertyChanged("role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<int> users_acts_id_user_act {
            get {
                return this.users_acts_id_user_actField;
            }
            set {
                if ((object.ReferenceEquals(this.users_acts_id_user_actField, value) != true)) {
                    this.users_acts_id_user_actField = value;
                    this.RaisePropertyChanged("users_acts_id_user_act");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<int> users_workgroups_id_users_workgroups {
            get {
                return this.users_workgroups_id_users_workgroupsField;
            }
            set {
                if ((object.ReferenceEquals(this.users_workgroups_id_users_workgroupsField, value) != true)) {
                    this.users_workgroups_id_users_workgroupsField = value;
                    this.RaisePropertyChanged("users_workgroups_id_users_workgroups");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceListarTodosLosUsers.IUsersService")]
    public interface IUsersService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/InsertarUsers", ReplyAction="http://tempuri.org/IUsersService/InsertarUsersResponse")]
        string InsertarUsers(SignalDBClienteServicios.ServiceReferenceListarTodosLosUsers.usersDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/InsertarUsers", ReplyAction="http://tempuri.org/IUsersService/InsertarUsersResponse")]
        System.Threading.Tasks.Task<string> InsertarUsersAsync(SignalDBClienteServicios.ServiceReferenceListarTodosLosUsers.usersDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/ActualizarUsers", ReplyAction="http://tempuri.org/IUsersService/ActualizarUsersResponse")]
        bool ActualizarUsers(SignalDBClienteServicios.ServiceReferenceListarTodosLosUsers.usersDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/ActualizarUsers", ReplyAction="http://tempuri.org/IUsersService/ActualizarUsersResponse")]
        System.Threading.Tasks.Task<bool> ActualizarUsersAsync(SignalDBClienteServicios.ServiceReferenceListarTodosLosUsers.usersDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/EliminarUsers", ReplyAction="http://tempuri.org/IUsersService/EliminarUsersResponse")]
        bool EliminarUsers(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/EliminarUsers", ReplyAction="http://tempuri.org/IUsersService/EliminarUsersResponse")]
        System.Threading.Tasks.Task<bool> EliminarUsersAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/BuscarUsers", ReplyAction="http://tempuri.org/IUsersService/BuscarUsersResponse")]
        SignalDBClienteServicios.ServiceReferenceListarTodosLosUsers.usersDTO BuscarUsers(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/BuscarUsers", ReplyAction="http://tempuri.org/IUsersService/BuscarUsersResponse")]
        System.Threading.Tasks.Task<SignalDBClienteServicios.ServiceReferenceListarTodosLosUsers.usersDTO> BuscarUsersAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/ListarUsers", ReplyAction="http://tempuri.org/IUsersService/ListarUsersResponse")]
        System.Collections.Generic.List<SignalDBClienteServicios.ServiceReferenceListarTodosLosUsers.usersDTO> ListarUsers(string param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/ListarUsers", ReplyAction="http://tempuri.org/IUsersService/ListarUsersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SignalDBClienteServicios.ServiceReferenceListarTodosLosUsers.usersDTO>> ListarUsersAsync(string param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/ListarTodosLosUsers", ReplyAction="http://tempuri.org/IUsersService/ListarTodosLosUsersResponse")]
        System.Collections.Generic.List<SignalDBClienteServicios.ServiceReferenceListarTodosLosUsers.usersDTO> ListarTodosLosUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/ListarTodosLosUsers", ReplyAction="http://tempuri.org/IUsersService/ListarTodosLosUsersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SignalDBClienteServicios.ServiceReferenceListarTodosLosUsers.usersDTO>> ListarTodosLosUsersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsersServiceChannel : SignalDBClienteServicios.ServiceReferenceListarTodosLosUsers.IUsersService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsersServiceClient : System.ServiceModel.ClientBase<SignalDBClienteServicios.ServiceReferenceListarTodosLosUsers.IUsersService>, SignalDBClienteServicios.ServiceReferenceListarTodosLosUsers.IUsersService {
        
        public UsersServiceClient() {
        }
        
        public UsersServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsersServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertarUsers(SignalDBClienteServicios.ServiceReferenceListarTodosLosUsers.usersDTO dto) {
            return base.Channel.InsertarUsers(dto);
        }
        
        public System.Threading.Tasks.Task<string> InsertarUsersAsync(SignalDBClienteServicios.ServiceReferenceListarTodosLosUsers.usersDTO dto) {
            return base.Channel.InsertarUsersAsync(dto);
        }
        
        public bool ActualizarUsers(SignalDBClienteServicios.ServiceReferenceListarTodosLosUsers.usersDTO dto) {
            return base.Channel.ActualizarUsers(dto);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarUsersAsync(SignalDBClienteServicios.ServiceReferenceListarTodosLosUsers.usersDTO dto) {
            return base.Channel.ActualizarUsersAsync(dto);
        }
        
        public bool EliminarUsers(string id) {
            return base.Channel.EliminarUsers(id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarUsersAsync(string id) {
            return base.Channel.EliminarUsersAsync(id);
        }
        
        public SignalDBClienteServicios.ServiceReferenceListarTodosLosUsers.usersDTO BuscarUsers(string id) {
            return base.Channel.BuscarUsers(id);
        }
        
        public System.Threading.Tasks.Task<SignalDBClienteServicios.ServiceReferenceListarTodosLosUsers.usersDTO> BuscarUsersAsync(string id) {
            return base.Channel.BuscarUsersAsync(id);
        }
        
        public System.Collections.Generic.List<SignalDBClienteServicios.ServiceReferenceListarTodosLosUsers.usersDTO> ListarUsers(string param) {
            return base.Channel.ListarUsers(param);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SignalDBClienteServicios.ServiceReferenceListarTodosLosUsers.usersDTO>> ListarUsersAsync(string param) {
            return base.Channel.ListarUsersAsync(param);
        }
        
        public System.Collections.Generic.List<SignalDBClienteServicios.ServiceReferenceListarTodosLosUsers.usersDTO> ListarTodosLosUsers() {
            return base.Channel.ListarTodosLosUsers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SignalDBClienteServicios.ServiceReferenceListarTodosLosUsers.usersDTO>> ListarTodosLosUsersAsync() {
            return base.Channel.ListarTodosLosUsersAsync();
        }
    }
}
