//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/04/19 - 13:27:59
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Dominio.Dtos;
using PersistenciaDatos;

namespace Dominio.Convertidores
{

    /// <summary>
    /// Assembler for <see cref="acts_files"/> and <see cref="acts_filesDTO"/>.
    /// </summary>
    public static partial class acts_filesCONVERTIDOR
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="acts_filesDTO"/> converted from <see cref="acts_files"/>.</param>
        static partial void OnDTO(this acts_files entity, acts_filesDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="acts_files"/> converted from <see cref="acts_filesDTO"/>.</param>
        static partial void OnEntity(this acts_filesDTO dto, acts_files entity);

        /// <summary>
        /// Converts this instance of <see cref="acts_filesDTO"/> to an instance of <see cref="acts_files"/>.
        /// </summary>
        /// <param name="dto"><see cref="acts_filesDTO"/> to convert.</param>
        public static acts_files ToEntity(this acts_filesDTO dto)
        {
            if (dto == null) return null;

            var entity = new acts_files();

            entity.id_acts_files = dto.id_acts_files;
            entity.id_act = dto.id_act;
            entity.id_file = dto.id_file;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="acts_files"/> to an instance of <see cref="acts_filesDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="acts_files"/> to convert.</param>
        public static acts_filesDTO ToDTO(this acts_files entity)
        {
            if (entity == null) return null;

            var dto = new acts_filesDTO();

            dto.id_acts_files = entity.id_acts_files;
            dto.id_act = entity.id_act;
            dto.id_file = entity.id_file;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="acts_filesDTO"/> to an instance of <see cref="acts_files"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<acts_files> ToEntities(this IEnumerable<acts_filesDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="acts_files"/> to an instance of <see cref="acts_filesDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<acts_filesDTO> ToDTOs(this IEnumerable<acts_files> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
