//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/04/19 - 13:28:00
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Dominio.Dtos;
using PersistenciaDatos;

namespace Dominio.Convertidores
{

    /// <summary>
    /// Assembler for <see cref="agreements"/> and <see cref="agreementsDTO"/>.
    /// </summary>
    public static partial class agreementsCONVERTIDOR
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="agreementsDTO"/> converted from <see cref="agreements"/>.</param>
        static partial void OnDTO(this agreements entity, agreementsDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="agreements"/> converted from <see cref="agreementsDTO"/>.</param>
        static partial void OnEntity(this agreementsDTO dto, agreements entity);

        /// <summary>
        /// Converts this instance of <see cref="agreementsDTO"/> to an instance of <see cref="agreements"/>.
        /// </summary>
        /// <param name="dto"><see cref="agreementsDTO"/> to convert.</param>
        public static agreements ToEntity(this agreementsDTO dto)
        {
            if (dto == null) return null;

            var entity = new agreements();

            entity.id_act = dto.id_act;
            entity.name = dto.name;
            entity.description = dto.description;
            entity.id_user_responsible = dto.id_user_responsible;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="agreements"/> to an instance of <see cref="agreementsDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="agreements"/> to convert.</param>
        public static agreementsDTO ToDTO(this agreements entity)
        {
            if (entity == null) return null;

            var dto = new agreementsDTO();

            dto.id_act = entity.id_act;
            dto.name = entity.name;
            dto.description = entity.description;
            dto.id_user_responsible = entity.id_user_responsible;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="agreementsDTO"/> to an instance of <see cref="agreements"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<agreements> ToEntities(this IEnumerable<agreementsDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="agreements"/> to an instance of <see cref="agreementsDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<agreementsDTO> ToDTOs(this IEnumerable<agreements> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
