//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/04/19 - 13:27:54
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Dominio.Dtos
{
    [DataContract()]
    public partial class actsDTO
    {
        [DataMember()]
        public Int32 id_act { get; set; }

        [DataMember()]
        public String name_act { get; set; }

        [DataMember()]
        public DateTime create_date { get; set; }

        [DataMember()]
        public Nullable<Int32> status { get; set; }

        [DataMember()]
        public String description_small { get; set; }

        [DataMember()]
        public String description_large { get; set; }

        [DataMember()]
        public String id_user_create { get; set; }

        [DataMember()]
        public List<Int32> acts_files_id_acts_files { get; set; }

        [DataMember()]
        public List<agreementsDTO> agreements { get; set; }

        [DataMember()]
        public List<Int32> messages_id_message { get; set; }

        [DataMember()]
        public List<Int32> users_acts_id_user_act { get; set; }

        public actsDTO()
        {
        }

        public actsDTO(Int32 id_act, String name_act, DateTime create_date, Nullable<Int32> status, String description_small, String description_large, String id_user_create, List<Int32> acts_files_id_acts_files, List<agreementsDTO> agreements, List<Int32> messages_id_message, List<Int32> users_acts_id_user_act)
        {
			this.id_act = id_act;
			this.name_act = name_act;
			this.create_date = create_date;
			this.status = status;
			this.description_small = description_small;
			this.description_large = description_large;
			this.id_user_create = id_user_create;
			this.acts_files_id_acts_files = acts_files_id_acts_files;
			this.agreements = agreements;
			this.messages_id_message = messages_id_message;
			this.users_acts_id_user_act = users_acts_id_user_act;
        }
    }
}
