//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/04/19 - 13:27:55
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Dominio.Dtos
{
    [DataContract()]
    public partial class acts_filesDTO
    {
        [DataMember()]
        public Int32 id_acts_files { get; set; }

        [DataMember()]
        public Int32 id_act { get; set; }

        [DataMember()]
        public Int32 id_file { get; set; }

        [DataMember()]
        public Int32 acts_id_act { get; set; }

        [DataMember()]
        public Int32 files_id_file { get; set; }

        public acts_filesDTO()
        {
        }

        public acts_filesDTO(Int32 id_acts_files, Int32 id_act, Int32 id_file, Int32 acts_id_act, Int32 files_id_file)
        {
			this.id_acts_files = id_acts_files;
			this.id_act = id_act;
			this.id_file = id_file;
			this.acts_id_act = acts_id_act;
			this.files_id_file = files_id_file;
        }
    }
}
