//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/04/19 - 13:27:55
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Dominio.Dtos
{
    [DataContract()]
    public partial class agreementsDTO
    {
        [DataMember()]
        public Int32 id_act { get; set; }

        [DataMember()]
        public String name { get; set; }

        [DataMember()]
        public String description { get; set; }

        [DataMember()]
        public String id_user_responsible { get; set; }

        [DataMember()]
        public Int32 acts_id_act { get; set; }

        public agreementsDTO()
        {
        }

        public agreementsDTO(Int32 id_act, String name, String description, String id_user_responsible, Int32 acts_id_act)
        {
			this.id_act = id_act;
			this.name = name;
			this.description = description;
			this.id_user_responsible = id_user_responsible;
			this.acts_id_act = acts_id_act;
        }
    }
}
