//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/04/19 - 13:27:55
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Dominio.Dtos
{
    [DataContract()]
    public partial class departmentsDTO
    {
        [DataMember()]
        public Int32 id_department { get; set; }

        [DataMember()]
        public String name { get; set; }

        [DataMember()]
        public String description { get; set; }

        [DataMember()]
        public List<String> users_id_user { get; set; }

        public departmentsDTO()
        {
        }

        public departmentsDTO(Int32 id_department, String name, String description, List<String> users_id_user)
        {
			this.id_department = id_department;
			this.name = name;
			this.description = description;
			this.users_id_user = users_id_user;
        }
    }
}
