//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/04/19 - 13:27:56
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Dominio.Dtos
{
    [DataContract()]
    public partial class filesDTO
    {
        [DataMember()]
        public Int32 id_file { get; set; }

        [DataMember()]
        public String name_file { get; set; }

        [DataMember()]
        public DateTime adjunt_date { get; set; }

        [DataMember()]
        public Nullable<Int32> status { get; set; }

        [DataMember()]
        public String type { get; set; }

        [DataMember()]
        public Nullable<DateTime> modify_date { get; set; }

        [DataMember()]
        public String address { get; set; }

        [DataMember()]
        public List<Int32> acts_files_id_acts_files { get; set; }

        [DataMember()]
        public List<Int32> messages_files_id_messages_files { get; set; }

        public filesDTO()
        {
        }

        public filesDTO(Int32 id_file, String name_file, DateTime adjunt_date, Nullable<Int32> status, String type, Nullable<DateTime> modify_date, String address, List<Int32> acts_files_id_acts_files, List<Int32> messages_files_id_messages_files)
        {
			this.id_file = id_file;
			this.name_file = name_file;
			this.adjunt_date = adjunt_date;
			this.status = status;
			this.type = type;
			this.modify_date = modify_date;
			this.address = address;
			this.acts_files_id_acts_files = acts_files_id_acts_files;
			this.messages_files_id_messages_files = messages_files_id_messages_files;
        }
    }
}
