//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/04/19 - 13:27:56
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Dominio.Dtos
{
    [DataContract()]
    public partial class messagesDTO
    {
        [DataMember()]
        public Int32 id_message { get; set; }

        [DataMember()]
        public String from_user_id { get; set; }

        [DataMember()]
        public String to_user_id { get; set; }

        [DataMember()]
        public String subject { get; set; }

        [DataMember()]
        public String contentx { get; set; }

        [DataMember()]
        public DateTime create_date { get; set; }

        [DataMember()]
        public Nullable<Int32> unread { get; set; }

        [DataMember()]
        public Nullable<Int32> status { get; set; }

        [DataMember()]
        public Nullable<Int32> id_workgroup { get; set; }

        [DataMember()]
        public Nullable<Int32> id_act { get; set; }

        [DataMember()]
        public Int32 acts_id_act { get; set; }

        [DataMember()]
        public List<Int32> messages_files_id_messages_files { get; set; }

        [DataMember()]
        public String users_id_user { get; set; }

        [DataMember()]
        public String users1_id_user { get; set; }

        [DataMember()]
        public Int32 workgroups_id_workgroup { get; set; }

        public messagesDTO()
        {
        }

        public messagesDTO(Int32 id_message, String from_user_id, String to_user_id, String subject, String contentx, DateTime create_date, Nullable<Int32> unread, Nullable<Int32> status, Nullable<Int32> id_workgroup, Nullable<Int32> id_act, Int32 acts_id_act, List<Int32> messages_files_id_messages_files, String users_id_user, String users1_id_user, Int32 workgroups_id_workgroup)
        {
			this.id_message = id_message;
			this.from_user_id = from_user_id;
			this.to_user_id = to_user_id;
			this.subject = subject;
			this.contentx = contentx;
			this.create_date = create_date;
			this.unread = unread;
			this.status = status;
			this.id_workgroup = id_workgroup;
			this.id_act = id_act;
			this.acts_id_act = acts_id_act;
			this.messages_files_id_messages_files = messages_files_id_messages_files;
			this.users_id_user = users_id_user;
			this.users1_id_user = users1_id_user;
			this.workgroups_id_workgroup = workgroups_id_workgroup;
        }
    }
}
