//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/04/19 - 13:27:57
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Dominio.Dtos
{
    [DataContract()]
    public partial class messages_filesDTO
    {
        [DataMember()]
        public Int32 id_messages_files { get; set; }

        [DataMember()]
        public Int32 id_message { get; set; }

        [DataMember()]
        public Int32 id_file { get; set; }

        [DataMember()]
        public Int32 files_id_file { get; set; }

        [DataMember()]
        public Int32 messages_id_message { get; set; }

        public messages_filesDTO()
        {
        }

        public messages_filesDTO(Int32 id_messages_files, Int32 id_message, Int32 id_file, Int32 files_id_file, Int32 messages_id_message)
        {
			this.id_messages_files = id_messages_files;
			this.id_message = id_message;
			this.id_file = id_file;
			this.files_id_file = files_id_file;
			this.messages_id_message = messages_id_message;
        }
    }
}
