//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/04/19 - 13:27:58
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Dominio.Dtos
{
    [DataContract()]
    public partial class users_actsDTO
    {
        [DataMember()]
        public Int32 id_user_act { get; set; }

        [DataMember()]
        public Int32 id_act { get; set; }

        [DataMember()]
        public String id_user { get; set; }

        [DataMember()]
        public Int32 acts_id_act { get; set; }

        [DataMember()]
        public String users_id_user { get; set; }

        public users_actsDTO()
        {
        }

        public users_actsDTO(Int32 id_user_act, Int32 id_act, String id_user, Int32 acts_id_act, String users_id_user)
        {
			this.id_user_act = id_user_act;
			this.id_act = id_act;
			this.id_user = id_user;
			this.acts_id_act = acts_id_act;
			this.users_id_user = users_id_user;
        }
    }
}
