//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/04/19 - 13:27:58
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Dominio.Dtos
{
    [DataContract()]
    public partial class users_workgroupsDTO
    {
        [DataMember()]
        public Int32 id_users_workgroups { get; set; }

        [DataMember()]
        public Int32 id_workgroup { get; set; }

        [DataMember()]
        public String id_user { get; set; }

        [DataMember()]
        public String users_id_user { get; set; }

        [DataMember()]
        public Int32 workgroups_id_workgroup { get; set; }

        public users_workgroupsDTO()
        {
        }

        public users_workgroupsDTO(Int32 id_users_workgroups, Int32 id_workgroup, String id_user, String users_id_user, Int32 workgroups_id_workgroup)
        {
			this.id_users_workgroups = id_users_workgroups;
			this.id_workgroup = id_workgroup;
			this.id_user = id_user;
			this.users_id_user = users_id_user;
			this.workgroups_id_workgroup = workgroups_id_workgroup;
        }
    }
}
