//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/04/19 - 13:27:57
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Dominio.Dtos
{
    [DataContract()]
    public partial class usersDTO
    {
        [DataMember()]
        public String id_user { get; set; }

        [DataMember()]
        public String username { get; set; }

        [DataMember()]
        public String fullname { get; set; }

        [DataMember()]
        public String password { get; set; }

        [DataMember()]
        public DateTime create_date { get; set; }

        [DataMember()]
        public Nullable<DateTime> last_acces_datex { get; set; }

        [DataMember()]
        public Nullable<Int32> status { get; set; }

        [DataMember()]
        public String mail { get; set; }

        [DataMember()]
        public DateTime date_of_birth { get; set; }

        [DataMember()]
        public String profession { get; set; }

        [DataMember()]
        public Nullable<Int32> id_department { get; set; }

        [DataMember()]
        public Int32 role { get; set; }

        [DataMember()]
        public Int32 departments_id_department { get; set; }

        [DataMember()]
        public List<Int32> messages_id_message { get; set; }

        [DataMember()]
        public List<Int32> messages1_id_message { get; set; }

        [DataMember()]
        public List<Int32> users_acts_id_user_act { get; set; }

        [DataMember()]
        public List<Int32> users_workgroups_id_users_workgroups { get; set; }

        public usersDTO()
        {
        }

        public usersDTO(String id_user, String username, String fullname, String password, DateTime create_date, Nullable<DateTime> last_acces_datex, Nullable<Int32> status, String mail, DateTime date_of_birth, String profession, Nullable<Int32> id_department, Int32 role, Int32 departments_id_department, List<Int32> messages_id_message, List<Int32> messages1_id_message, List<Int32> users_acts_id_user_act, List<Int32> users_workgroups_id_users_workgroups)
        {
			this.id_user = id_user;
			this.username = username;
			this.fullname = fullname;
			this.password = password;
			this.create_date = create_date;
			this.last_acces_datex = last_acces_datex;
			this.status = status;
			this.mail = mail;
			this.date_of_birth = date_of_birth;
			this.profession = profession;
			this.id_department = id_department;
			this.role = role;
			this.departments_id_department = departments_id_department;
			this.messages_id_message = messages_id_message;
			this.messages1_id_message = messages1_id_message;
			this.users_acts_id_user_act = users_acts_id_user_act;
			this.users_workgroups_id_users_workgroups = users_workgroups_id_users_workgroups;
        }
    }
}
