//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/04/19 - 13:27:59
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Dominio.Dtos
{
    [DataContract()]
    public partial class workgroupsDTO
    {
        [DataMember()]
        public Int32 id_workgroup { get; set; }

        [DataMember()]
        public String name_workgroup { get; set; }

        [DataMember()]
        public DateTime create_date { get; set; }

        [DataMember()]
        public Nullable<Int32> status { get; set; }

        [DataMember()]
        public String description { get; set; }

        [DataMember()]
        public List<Int32> messages_id_message { get; set; }

        [DataMember()]
        public List<Int32> users_workgroups_id_users_workgroups { get; set; }

        public workgroupsDTO()
        {
        }

        public workgroupsDTO(Int32 id_workgroup, String name_workgroup, DateTime create_date, Nullable<Int32> status, String description, List<Int32> messages_id_message, List<Int32> users_workgroups_id_users_workgroups)
        {
			this.id_workgroup = id_workgroup;
			this.name_workgroup = name_workgroup;
			this.create_date = create_date;
			this.status = status;
			this.description = description;
			this.messages_id_message = messages_id_message;
			this.users_workgroups_id_users_workgroups = users_workgroups_id_users_workgroups;
        }
    }
}
