//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class acts
    {
        public acts()
        {
            this.acts_files = new HashSet<acts_files>();
            this.agreements = new HashSet<agreements>();
            this.messages = new HashSet<messages>();
            this.users_acts = new HashSet<users_acts>();
        }
    
        public int id_act { get; set; }
        public string name_act { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<int> status { get; set; }
        public string description_small { get; set; }
        public string description_large { get; set; }
        public string id_user_create { get; set; }
    
        public virtual ICollection<acts_files> acts_files { get; set; }
        public virtual ICollection<agreements> agreements { get; set; }
        public virtual ICollection<messages> messages { get; set; }
        public virtual ICollection<users_acts> users_acts { get; set; }
    }
}
