//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class agreements
    {
        public int id_act { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string id_user_responsible { get; set; }
    
        public virtual acts acts { get; set; }
    }
}
