//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class files
    {
        public files()
        {
            this.acts_files = new HashSet<acts_files>();
            this.messages_files = new HashSet<messages_files>();
        }
    
        public int id_file { get; set; }
        public string name_file { get; set; }
        public System.DateTime adjunt_date { get; set; }
        public Nullable<int> status { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string address { get; set; }
    
        public virtual ICollection<acts_files> acts_files { get; set; }
        public virtual ICollection<messages_files> messages_files { get; set; }
    }
}
