//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class messages
    {
        public messages()
        {
            this.messages_files = new HashSet<messages_files>();
        }
    
        public int id_message { get; set; }
        public string from_user_id { get; set; }
        public string to_user_id { get; set; }
        public string subject { get; set; }
        public string contentx { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<int> unread { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> id_workgroup { get; set; }
        public Nullable<int> id_act { get; set; }
    
        public virtual acts acts { get; set; }
        public virtual ICollection<messages_files> messages_files { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
        public virtual workgroups workgroups { get; set; }
    }
}
