//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SignalDBEntities : DbContext
    {
        public SignalDBEntities()
            : base("name=SignalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<acts> acts { get; set; }
        public DbSet<acts_files> acts_files { get; set; }
        public DbSet<agreements> agreements { get; set; }
        public DbSet<departments> departments { get; set; }
        public DbSet<files> files { get; set; }
        public DbSet<messages> messages { get; set; }
        public DbSet<messages_files> messages_files { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<users_acts> users_acts { get; set; }
        public DbSet<users_workgroups> users_workgroups { get; set; }
        public DbSet<workgroups> workgroups { get; set; }
    }
}
