//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.messages = new HashSet<messages>();
            this.messages1 = new HashSet<messages>();
            this.users_acts = new HashSet<users_acts>();
            this.users_workgroups = new HashSet<users_workgroups>();
        }
    
        public string id_user { get; set; }
        public string username { get; set; }
        public string fullname { get; set; }
        public string password { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<System.DateTime> last_acces_datex { get; set; }
        public Nullable<int> status { get; set; }
        public string mail { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public string profession { get; set; }
        public Nullable<int> id_department { get; set; }
        public int role { get; set; }
    
        public virtual departments departments { get; set; }
        public virtual ICollection<messages> messages { get; set; }
        public virtual ICollection<messages> messages1 { get; set; }
        public virtual ICollection<users_acts> users_acts { get; set; }
        public virtual ICollection<users_workgroups> users_workgroups { get; set; }
    }
}
