//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class workgroups
    {
        public workgroups()
        {
            this.messages = new HashSet<messages>();
            this.users_workgroups = new HashSet<users_workgroups>();
        }
    
        public int id_workgroup { get; set; }
        public string name_workgroup { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<int> status { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<messages> messages { get; set; }
        public virtual ICollection<users_workgroups> users_workgroups { get; set; }
    }
}
